### ISSUE TITLE
centos7 运行失败

### ISSUE THREAD

**Issue by JXT-Eden** [3xxx/engineercms#13]
您好，安装好docker和onlyoffice,下载engineercms linux版的源码和可执行程序，在源码目录下运行报错
错误信息如下：
2018/11/08 18:40:27.194 [E] [template.go:174]  parse template err: index.tpl template: index.tpl:46: function "loadtimes" not defined
11/08 18:40:27.194 [W] [beego.go:100]  template: index.tpl:46: function "loadtimes" not defined
panic: template: index.tpl:46: function "loadtimes" not defined
goroutine 1 [running]:
github.com/astaxie/beego.initBeforeHTTPRun()
	/home/ubuntu/go/src/github.com/astaxie/beego/beego.go:101 +0x215
github.com/astaxie/beego.Run(0x0, 0x0, 0x0)
	/home/ubuntu/go/src/github.com/astaxie/beego/beego.go:55 +0x26
main.main()
	/home/ubuntu/go/src/github.com/3xxx/EngineerCMS/main.go:30 +0x251

**Comment by 3xxx** [comment]
嗯，对的。请下载最新版的linux版，在网盘里。或者你讲index.tpl里的loadtimes删除掉。

**Comment by cjimkon** [comment]
你好，请问这样 是什么问题

goroutine 1 [running]:
github.com/astaxie/beego.(*ControllerRegister).Include(0xc0000b34a0, 0xc0002217c0, 0x1, 0x1)
        /root/gocode/src/github.com/astaxie/beego/router.go:257 +0x9d1
github.com/astaxie/beego.(*Namespace).Include(0xc000236280, 0xc0002217c0, 0x1, 0x1, 0xc000236280)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:186 +0x4d
github.com/astaxie/beego.NSInclude.func1(0xc000236280)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:302 +0x46
github.com/astaxie/beego.NewNamespace(0x139923a, 0x6, 0xc00000f098, 0x1, 0x1, 0xc0001c1f01)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:42 +0x87
github.com/astaxie/beego.NSNamespace.func1(0xc000236260)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:386 +0x52
github.com/astaxie/beego.NewNamespace(0x13955f9, 0x3, 0xc000149f50, 0x3, 0x3, 0xc0001c1f20)
        /root/gocode/src/github.com/astaxie/beego/namespace.go:42 +0x87
github.com/3xxx/engineercms/routers.init.2()
        /root/gocode/src/github.com/3xxx/engineercms/routers/router.go:26 +0x6bd

**Comment by 3xxx** [comment]
@cjimkon 感觉是环境问题，安装beego了吗？

**Comment by cjimkon** [comment]
已经 搞定了，非常感谢

hotqin888 <notifications@github.com> 于2019年3月2日周六 下午11:08写道：
